package com.ovi.where.core.notification

import android.content.Context
import android.media.RingtoneManager
import android.net.Uri
import androidx.annotation.RawRes
import androidx.core.net.toUri
import com.ovi.where.R

/**
 * Built-in notification sounds shipped with the app, plus a couple of
 * synthetic options (system default + silent).
 *
 * Each entry maps to a raw resource under `res/raw/` (generated by
 * `scripts/generate_notification_sounds.py`). The id is what we persist
 * in DataStore — never the resource int — so renaming files doesn't
 * orphan saved preferences.
 *
 * `Default` falls back to the device's default notification ringtone
 * (RingtoneManager.TYPE_NOTIFICATION). `Silent` produces no sound at
 * channel-creation time (channel.setSound(null)), which on O+ also
 * disables vibration / lights for that channel.
 */
enum class NotificationSound(
    val id: String,
    @RawRes val rawRes: Int?,
    val displayName: String,
    val description: String
) {
    Default(
        id = "default",
        rawRes = null,
        displayName = "System default",
        description = "Use the device's default notification sound"
    ),
    Chat(
        id = "where_chat",
        rawRes = R.raw.where_chat,
        displayName = "Where Chat",
        description = "Bright two-note ping for new messages"
    ),
    Mention(
        id = "where_mention",
        rawRes = R.raw.where_mention,
        displayName = "Where Mention",
        description = "Layered chime — designed to grab attention"
    ),
    Friend(
        id = "where_friend",
        rawRes = R.raw.where_friend,
        displayName = "Where Friend",
        description = "Soft major-third chord for friend activity"
    ),
    Meetup(
        id = "where_meetup",
        rawRes = R.raw.where_meetup,
        displayName = "Where Meetup",
        description = "Ascending arpeggio for meetup events and arrivals"
    ),
    Location(
        id = "where_location",
        rawRes = R.raw.where_location,
        displayName = "Where Location",
        description = "Quiet pulse for live-location updates"
    ),
    General(
        id = "where_general",
        rawRes = R.raw.where_general,
        displayName = "Where General",
        description = "Classic two-note ping"
    ),
    Silent(
        id = "silent",
        rawRes = null,
        displayName = "Silent",
        description = "No sound (notifications still appear in the shade)"
    );

    /**
     * Returns the [Uri] to feed into `NotificationChannel.setSound(...)`,
     * or `null` to indicate "no sound" — the channel must be created with
     * `setSound(null, null)` for silent operation.
     */
    fun resolveUri(context: Context): Uri? = when (this) {
        Silent -> null
        Default -> RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION)
        else -> rawRes?.let {
            "android.resource://${context.packageName}/$it".toUri()
        }
    }

    companion object {
        /** Lookup by stable id; returns [Default] when the id is unknown. */
        fun fromId(id: String?): NotificationSound =
            entries.firstOrNull { it.id == id } ?: Default

        /**
         * Suggested sound for a given channel — the first time the user
         * lands on the settings screen, this is what's selected for each
         * category. Picks the most semantically aligned tone so users
         * who never touch the picker still hear category-appropriate
         * audio cues.
         */
        fun defaultFor(channelId: String): NotificationSound = when (channelId) {
            NotificationHelper.CHANNEL_MESSAGES -> Chat
            NotificationHelper.CHANNEL_SOCIAL -> Friend
            NotificationHelper.CHANNEL_LOCATION_UPDATES -> Location
            NotificationHelper.CHANNEL_GROUP_ACTIVITY -> General
            NotificationHelper.CHANNEL_MEETUP -> Meetup
            NotificationHelper.CHANNEL_GENERAL -> General
            else -> Default
        }
    }
}
